name: mewnu
description: A new Flutter project.



publish_to: "none" 











version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.3
  delayed_display: ^2.0.0
  flutter_card_swipper: ^0.4.0
  rx_notifier: ^1.1.0
  flutter_svg: ^0.22.0
  visibility_detector: ^0.2.0
  
  webview_flutter: ^2.0.7
  animated_text_kit: ^4.2.1
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter





flutter:
  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  

  assets:
    - assets/images/
    - assets/logo/
    - assets/icon/
    - assets/google/maps_style.txt
    - assets/images/png/
    - assets/icons/png/
    - assets/icons/svg/
    - assets/logos/

  fonts:
    - family: Red_Hat_Display
      fonts:
        - asset: assets/fonts/Red_Hat_Display/RedHatDisplay-Regular.ttf
        - asset: assets/fonts/Red_Hat_Display/RedHatDisplay-Bold.ttf
        - asset: assets/fonts/Red_Hat_Display/RedHatDisplay-Black.ttf
    - family: Red_Hat_Text
      fonts:
        - asset: assets/fonts/Red_Hat_Text/RedHatText-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
    - family: Anurati
      fonts:
        - asset: assets/fonts/Anurati-Regular.otf
    - family: FlutterIcons
      fonts:
        - asset: assets/fonts/FlutterIcons.ttf
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
    - family: MyFlutterApp2
      fonts:
        - asset: assets/fonts/MyFlutterApp2.ttf
    - family: RemottelyIcons
      fonts:
        - asset: assets/fonts/RemottelyIcons.ttf
    - family: Astronaut_PersonalUse
      fonts:
        - asset: assets/fonts/Astronaut_PersonalUse.otf
    - family: Public_Sans
      fonts:
        - asset: assets/fonts/Public_Sans/PublicSans-VariableFont_wght.ttf
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
        
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
